image: atlassian/default-image:2
pipelines:
  default:
    - step:
        name: Build
        script:
          - make docker-build-ms-authentication docker-export-ms-authentication
        artifacts:
          - ecommerce-ms-authentication.docker
        services:
          - docker
        caches:
          - docker
    - step:
        name: Unit tests
        script:
          - make docker-import-ms-authentication INPUTFILE_PATH=../ecommerce-ms-authentication.docker
          - make run-unit-tests VERSION=latest
        artifacts:
          - app/coverage/**
        services:
          - docker
    - step:
        name: Static analysis
        script:
          - make run-code-analysis
        services:
          - docker
    - step:
        name: E2e tests
        script:
          - make docker-import-ms-authentication INPUTFILE_PATH=../ecommerce-ms-authentication.docker
          - make run-e2e-tests VERSION=latest
        services:
          - docker
  tags:
    "*":
      - step:
          name: Build
          script:
            - make docker-build-ms-authentication docker-export-ms-authentication
          artifacts:
            - ecommerce-ms-authentication.docker
          services:
            - docker
          caches:
            - docker
      - step:
          name: Unit tests
          script:
            - make docker-import-ms-authentication INPUTFILE_PATH=../ecommerce-ms-authentication.docker
            - make run-unit-tests VERSION=latest
          artifacts:
            - app/coverage/**
          services:
            - docker
      - step:
          name: Static analysis
          script:
            - make run-code-analysis
          services:
            - docker
      - step:
          name: E2e tests
          script:
            - make docker-import-ms-authentication INPUTFILE_PATH=../ecommerce-ms-authentication.docker
            - make run-e2e-tests VERSION=latest
          services:
            - docker
      - step:
          name: Push to ECR
          script:
            - make docker-import-ms-authentication INPUTFILE_PATH=../ecommerce-ms-authentication.docker
            - make docker-login
            - make docker-package-ms-authentication docker-publish-ms-authentication VERSION="$BITBUCKET_TAG"
          services:
            - docker
definitions:
  services:
    docker:
      memory: 2048
